FROM webimp/php-72-apache

COPY flag /
COPY Fl3g_n0t_Here_dont_peek!!!!!.php /var/www/html
COPY images.php /var/www/html
COPY index.php /var/www/html
COPY upload.php /var/www/html
COPY run.sh /run_prevent_Gu3#sss_srRyeeeee_baibai.sh

RUN mkdir /var/www/uploads
RUN chmod 755 /var/www/html/upload.php
RUN chmod -R 777 /var/www/uploads

CMD [ "bash", "/run_prevent_Gu3#sss_srRyeeeee_baibai.sh" ]